config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"
  devise_for :students
  
  resources :charges
  get "code-paris-apply" => "pages#apply", as: :apply
  get "code-executive-bootcamp" => "pages#applied", as: :applied
  get "code-sign-in" => "pages#sign_in", as: :devise
  get "code-subscribed" => "charges#subscribed", as: :subscribed
  
  get "lessons/chapters" => "lessons#chapters", as: :chapters
  get "lessons/objectif" => "lessons#objective", as: :objective
  get "lessons/sublime-text" => "lessons#sublime", as: :sublime
  get "lessons/premiere-page-html" => "lessons#firstpage", as: :firstpage
  get "lessons/front-end" => "lessons#front", as: :front
  get "lessons/syntaxe-html" => "lessons#syntaxhtml", as: :syntaxhtml
  get "lessons/document-html-minimal" => "lessons#minimal", as: :minimal
  get "lessons/balises-classiques" => "lessons#commontags", as: :commontags
  get "lessons/attributs" => "lessons#attributes", as: :attributes
  get "lessons/html" => "lessons#html", as: :html
  get "lessons/css" => "lessons#css", as: :css
  get "lessons/syntaxe-css" => "lessons#syntaxcss", as: :syntaxcss
  get "lessons/ou-mettre-le-css" => "lessons#putcss", as: :putcss
  get "lessons/exemple-couple-propriete-valeur" => "lessons#properties", as: :properties
  get "lessons/selecteur-class" => "lessons#selector", as: :selector
  get "lessons/colorzilla" => "lessons#break", as: :break
  get "lessons/bootstrap" => "lessons#bootstrap", as: :bootstrap
  get "lessons/barre-de-navigation" => "lessons#navbar", as: :navbar
  get "lessons/grille" => "lessons#grid", as: :grid
  get "lessons/arriere-plan" => "lessons#background", as: :background
  get "lessons/box-model" => "lessons#boxmodel", as: :boxmodel
  get "lessons/centrer" => "lessons#center", as: :center
  get "lessons/police" => "lessons#police", as: :police
  get "lessons/icones" => "lessons#icones", as: :icones
  get "lessons/git" => "lessons#git", as: :git
  get "lessons/github" => "lessons#github", as: :github
  get "lessons/heroku" => "lessons#heroku", as: :heroku
  get "lessons/customiser" => "lessons#customiser", as: :custom
  get "lessons/social" => "lessons#social", as: :social
  get "lessons/seo" => "lessons#seo", as: :seo
  get "lessons/ligne-de-commande" => "lessons#command", as: :command
  get "fastlanguages" => "pages#fast", as: :fast
  get "cpi-codepin-cours2" => "pages#codepin2", as: :codepin2

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	  chapters_path
	end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def create

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       params[:amount],
      description:  'Formation Executive CodeCamp',
      currency:     'eur'
    )

    UserMailer.booking_confirmation(params[:stripeEmail]).deliver

    redirect_to subscribed_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_student!
  layout nil

  def chapters
  	render layout: nil
  end

  def objective
  	render layout: nil
  end

  def sublime
  	render layout: nil
  end

  def firstpage
  	render layout: nil
  end

  def front
  	render layout: nil
  end

  def syntaxhtml
  	render layout: nil
  end

  def minimal
  	render layout: nil
  end

  def commontags
  	render layout: nil
  end

  def attributes
  	render layout: nil
  end

  def html
  	render layout: nil
  end

  def css
  	render layout: nil
  end

  def syntaxcss
  	render layout: nil
  end

  def putcss
  	render layout: nil
  end

  def properties
  	render layout: nil
  end

  def selector
  	render layout: nil
  end

  def break
  	render layout: nil
  end

  def bootstrap
  	render layout: nil
  end

  def navbar
  	render layout: nil
  end

  def grid
  	render layout: nil
  end

  def background
  	render layout: nil
  end

  def boxmodel
  	render layout: nil
  end

  def center
  	render layout: nil
  end

  def police
  	render layout: nil
  end

  def icones
  	render layout: nil
  end

  def git
  	render layout: nil
  end

  def github
  	render layout: nil
  end

  def heroku
  	render layout: nil
  end

  def customiser
  	render layout: nil
  end

  def social
  	render layout: nil
  end

  def seo
  	render layout: nil
  end

  def command
  	render layout: nil
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @submitted = true if params[:email]
  end

  def apply
  end

  def applied
    UserMailer.booking_confirmation(params[:email]).deliver
    UserMailer.booking(params[:first_name], params[:last_name], params[:age], params[:email], params[:mobile_phone], params[:computer_pc], params[:computer_mac], params[:session], params[:expectations]).deliver
  end

  def sign_in
  end

  def fast
    render layout: nil
  end

  def codepin2
    render layout: nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :student
  end

  def resource
    @resource ||= Student.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:student]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header_lessons.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= h yield(:title) %></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="<%=h yield(:description) %>">
    <meta name="robots" content="NOODP">
    <meta name="keywords" content="apprendre, coder, Paris, formation, cours, Rails, HTML5, CSS, JavaScript, web, Design" />
    <meta name="google-site-verification" content="vjG2Ks9_3aOvtb-HE0lKEKfLBBqbCelw4axh8MlEo1M" />

    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link data-turbolinks-track="true" href="/assets/onemonth.css" media="all" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/assets/ruby.ico" />

    <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    
    <header class="navbar navbar-default navbar-static-top one-month-rails" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/lessons/chapters">CPi Code Academy</a>
        </div>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <nav class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
                
              <li class="dropdown">
                <a data-toggle="dropdown" href="#">
                  Tournaud<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
<!--              <li><a href="/users/edit">Profil</a></li>
     -->          <li>
                    <%= form_tag destroy_student_session_path, method: :delete, id: "logout_form" %>
                    <%= link_to 'Déconnexion', "#", id: "logout" %>
                  </li>
                  <script type="text/javascript">
                    $(document).ready(function(){
                      $('#logout').click(function(){
                          $('#logout_form').submit();
                      });
                    });
                  </script>
              
                </ul>
              </li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_nav.html.erb
<div id="nav-wrapper"> 
  <!-- Nav -->
  <nav id="nav">
    <ul>
      <li><a href="..">Accueil</a></li>
      <li id="apply"><%= link_to "NOS TUTORIELS", apply_path %></li>
      <% if student_signed_in? %>
        <li id="sign-in-nav"><div><%= link_to "Déconnexion", destroy_student_session_path, method: :delete %></div></li>
      <% else %>
      	<li id="sign-in-nav"><div><%= link_to "Espace Codeurs", devise_path %></div></li>
    	<% end %>
    </ul>
  </nav>
</div>

app/views/lessons/attributes.html.erb
<%= render 'layouts/header_lessons' %>

    <div class="container step-container">
      <div style="width:100%;">
        <div class="wistia_embed" id="wistia_qc62xzfpxe">
          <a href="/lessons/chapters"><img src="https://s3-eu-west-1.amazonaws.com/codepin/Navbar" alt="Bootstrap Navbar" class="imageLesson"></a>
        </div>
      </div>

      <ul class="list-inline">
        <li><h1>Les attributs des balises</h1></li>
        <li class="pull-right">
          <%= link_to "Terminer et continuer", html_path, class: "btn complete-btn one-month-rails" %>
        </li>
      </ul>

      
      <div class="tabbable">
      	<ul class="nav nav-tabs">
      		<li class="active">
      			<a data-toggle="tab" href="#step-notes">Support de cours</a>
      		</li>
          <li>
            <a data-toggle="tab" href="#troubleshooting">Code Associé</a>
          </li>
      		<li>
      			<a data-toggle="tab" href="#comments">Questions</a>
      		</li>
      	</ul>
      	<div class="tab-content">
      		<div class="tab-pane active" id="step-notes">
      		  <br>
            <p class="lead">Concept</p>
      		  <p>Bootstrap vous permet directement de copier-coller des:</p>
              <ul class="list-style">
                <li>barres de navigation</li>
                <li>onglets</li>
                <li>class pour disposer horizontalement vos listes</li>
                <li>boutons</li>
                <li>menus déroulants, ...</li>
              </ul>
            <h3>1. Récupérez l'élément</h3>
            <p>Rendez-vous sur <a href="http://getbootstrap.com/components/#navbar">http://getbootstrap.com/components/#navbar</a> et recherchez l'élément qu'il vous faut. Ici la navbar.</p>
            <p>Mais cherchez à droite si vous voulez plutôt gérer le style d'une image, de boutons, d'onglets, etc.</p>
            <p>Lisez la documentation et copiez le code de la navbar.</p>
            <p>Collez-le sous votre balise "body": vous avez une barre de navigation responsive! (faites changer la taille de l'écran cela devrait marcher).</p>
            <h3>2. Personnalisez l'élément</h3>
            <p>Il y a des chances que Bootstrap vous facilite la tâche, mais ne vous convienne pas tout à fait. Un peu comme les contours d'un dessin il faut maintenant colorier. Par exemple :
            <ul class="list-style">
              <li>supprimons:
                <ul class="list-style2">
                  <li>des liens</li>
                  <li>la zone de recherche</li>
                </ul>
              </li>
              <li>personnalisons:
                <ul class="list-style2">
                  <li>le nom des liens ("link" est moyen)</li>
                  <li>le reste (couleur, police, taille) prochainement!</li>
                </ul>
              </li>
            </ul>
            <br>
            <pre class="prettyprint">
&lt;nav class=&quot;navbar navbar-default&quot; role=&quot;navigation&quot;&gt;
  &lt;div class=&quot;container-fluid&quot;&gt;
    &lt;!-- Brand and toggle get grouped for better mobile display --&gt;
    &lt;div class=&quot;navbar-header&quot;&gt;
      &lt;button type=&quot;button&quot; class=&quot;navbar-toggle collapsed&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#bs-example-navbar-collapse-1&quot;&gt;
        &lt;span class=&quot;sr-only&quot;&gt;Toggle navigation&lt;/span&gt;
        &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
        &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
        &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
      &lt;/button&gt;
      &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;&lt;span&gt;CPi selfies&lt;span&gt;&lt;/a&gt;
    &lt;/div&gt;

    &lt;!-- Collect the nav links, forms, and other content for toggling --&gt;
    &lt;div class=&quot;collapse navbar-collapse&quot; id=&quot;bs-example-navbar-collapse-1&quot;&gt;
      &lt;ul class=&quot;nav navbar-nav navbar-right&quot;&gt;
        &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Contact&lt;/a&gt;&lt;/li&gt;
        &lt;li class=&quot;dropdown&quot;&gt;
          &lt;a href=&quot;#&quot; class=&quot;dropdown-toggle&quot; data-toggle=&quot;dropdown&quot;&gt;En savoir plus&lt;span class=&quot;caret&quot;&gt;&lt;/span&gt;&lt;/a&gt;
          &lt;ul class=&quot;dropdown-menu&quot; role=&quot;menu&quot;&gt;
            &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Presse&lt;/a&gt;&lt;/li&gt;
            &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Alumni&lt;/a&gt;&lt;/li&gt;
            &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Concours du meilleur selfie&lt;/a&gt;&lt;/li&gt;
            &lt;li class=&quot;divider&quot;&gt;&lt;/li&gt;
            &lt;li&gt;&lt;a href=&quot;#&quot;&gt;D&eacute;connexion&lt;/a&gt;&lt;/li&gt;
          &lt;/ul&gt;
        &lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;&lt;!-- /.navbar-collapse --&gt;
  &lt;/div&gt;&lt;!-- /.container-fluid --&gt;
&lt;/nav&gt;
            </pre>
      		</div>
      		<div class="tab-pane" id="troubleshooting">
            <div class='row'>
              <div class="col-xs-2">
                <br>
                <p><i class="fa fa-sort-desc"></i> MonSite</p>
                <p class="tab"><i class="fa fa-sort-desc"></i> css</p>
                <p class="tab2">cpi2.css</p>
                <p class="tab">index.html</p>
              </div>
              <div class="col-xs-10">
                <div class="tabbable subtab">
                  <ul class="nav nav-tabs">
                    <li class="active">
                      <a data-toggle="tab" href="#html">index.html</a>
                    </li>
                    <li>
                      <a data-toggle="tab" href="#css">cpi2.css</a>
                    </li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active" id="html">
                      <br>
                      <pre class="prettyprint">
&lt;!doctype html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;CPi selfies&lt;/title&gt;
    &lt;meta charset=&quot;utf-8&quot;&gt;
    
    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css&quot;&gt;

    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;assets/cpi2.css&quot;&gt;
  &lt;/head&gt;
  &lt;body&gt;

    &lt;div class=&quot;heading&quot;&gt;
      &lt;!-- Ma barre de navigation --&gt;
      &lt;nav class=&quot;navbar navbar-default&quot; role=&quot;navigation&quot;&gt;
        &lt;div class=&quot;container-fluid&quot;&gt;
          &lt;!-- Brand and toggle get grouped for better mobile display --&gt;
          &lt;div class=&quot;navbar-header&quot;&gt;
            &lt;button type=&quot;button&quot; class=&quot;navbar-toggle collapsed&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#bs-example-navbar-collapse-1&quot;&gt;
              &lt;span class=&quot;sr-only&quot;&gt;Toggle navigation&lt;/span&gt;
              &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
              &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
              &lt;span class=&quot;icon-bar&quot;&gt;&lt;/span&gt;
            &lt;/button&gt;
            &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;&lt;span&gt;CPi selfies&lt;span&gt;&lt;/a&gt;
          &lt;/div&gt;

          &lt;!-- Collect the nav links, forms, and other content for toggling --&gt;
          &lt;div class=&quot;collapse navbar-collapse&quot; id=&quot;bs-example-navbar-collapse-1&quot;&gt;
            &lt;ul class=&quot;nav navbar-nav navbar-right&quot;&gt;
              &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Contact&lt;/a&gt;&lt;/li&gt;
              &lt;li class=&quot;dropdown&quot;&gt;
                &lt;a href=&quot;#&quot; class=&quot;dropdown-toggle&quot; data-toggle=&quot;dropdown&quot;&gt;En savoir plus&lt;span class=&quot;caret&quot;&gt;&lt;/span&gt;&lt;/a&gt;
                &lt;ul class=&quot;dropdown-menu&quot; role=&quot;menu&quot;&gt;
                  &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Presse&lt;/a&gt;&lt;/li&gt;
                  &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Alumni&lt;/a&gt;&lt;/li&gt;
                  &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Concours du meilleur selfie&lt;/a&gt;&lt;/li&gt;
                  &lt;li class=&quot;divider&quot;&gt;&lt;/li&gt;
                  &lt;li&gt;&lt;a href=&quot;#&quot;&gt;D&eacute;connexion&lt;/a&gt;&lt;/li&gt;
                &lt;/ul&gt;
              &lt;/li&gt;
            &lt;/ul&gt;
          &lt;/div&gt;&lt;!-- /.navbar-collapse --&gt;
        &lt;/div&gt;&lt;!-- /.container-fluid --&gt;
      &lt;/nav&gt;

      &lt;h1&gt;Laissez-nous vos meilleurs selfies !&lt;/h1&gt;

      &lt;!-- J&#039;inclus jQuery dont le JavaScript de Bootstrap a besoin --&gt;
      &lt;script src="http://code.jquery.com/jquery-1.11.0.min.js"&gt; &lt;/script&gt;
      &lt;!-- J&#039;inclus le JavaScript de Bootstrap --&gt;
      &lt;script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"&gt; &lt;/script&gt;
    
  &lt;/body&gt;
&lt;/html&gt;
                      </pre>
                    </div>
                    <div class="tab-pane" id="css">
                      <br>
                      <pre class="prettyprint">
/*Aucun changement*/
                      </pre>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>                    
          <%= render 'layouts/lessons/disqus' %>
    		</div>
    	</div>
    </div>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        prettyPrint();
      });
    </script>
  </body>
</html>

app/views/lessons/center.html.erb
<%= render 'layouts/header_lessons' %>

    <div class="container step-container">
      <div style="width:100%;">
        <div class="wistia_embed" id="wistia_qc62xzfpxe">
          <a href="/"><img src="https://s3-eu-west-1.amazonaws.com/codepin/Block" alt="Bootstrap" class="imageLesson"></a>
        </div>
      </div>

      <ul class="list-inline">
        <li><h1>Centrer en CSS</h1></li>
        <li class="pull-right">
          <%= link_to "Terminer et continuer", police_path, class: "btn complete-btn one-month-rails" %>
        </li>
      </ul>

      <div class="tabbable">
      	<ul class="nav nav-tabs">
      		<li class="active">
      			<a data-toggle="tab" href="#step-notes">Support de cours</a>
      		</li>
          <li>
            <a data-toggle="tab" href="#troubleshooting">Code Associé</a>
          </li>
      		<li>
      			<a data-toggle="tab" href="#comments">Questions</a>
      		</li>
      	</ul>
      	<div class="tab-content">
      		<div class="tab-pane active" id="step-notes">
      		  <br>
      		  <p class="lead">Centrons verticalement, horizontalement. C'est plus compliqué qu'il n'y paraît.</p>
            <h3>1. Inline vs Block</h3>
            <p>En HTML tout élément est soit de type block, soit de type inline.</p>
            <h4>Block</h4>
            <p>Les éléments de type block prennent 100% de la largeur disponible et se placent les uns sous les autres (exemple: le paragraphe). Ils peuvent contenir d'autres éléments block et des éléments inline indifféremment.</p>
            <h4>Inline</h4>
            <p>Les éléments de type inline occupent seulement la largeur nécessaire et se placent les uns à la suite des autres (exemple: la mise en évidence d'un mot avec strong). Ils ne peuvent pas contenir d'éléments de type block, seulement des éléments inline.</p>

            <div class="panel panel-default">

              <!-- Table -->
              <table class="table table-bordered center">
                <th class="center">Eléments Block</th>
                <th class="center">Eléments Inline</th>
                <tr>
                  <td>h1, h2, ..., h6</td>
                  <td>strong</td>
                </tr>
                <tr>
                  <td>p</td>
                  <td>a</td>
                </tr>
                <tr>
                  <td>header, article, section, footer, nav</td>
                  <td>img</td>
                </tr>
                <tr>
                  <td>ul, ol</td>
                  <td>em</td>
                </tr>
                <tr>
                  <td>div</td>
                  <td>span</td>
                </tr>
              </table>
            </div>

            <h4>Inline-block</h4>
            <p>Les éléments de type inline-block contrôlent leur largeur (comme des blocks) et se placent les uns à coté des autres (inline).</p>
            <h4>Les éléments de type inline</h4>
            <pre class="prettyprint">
text-align: center;
            </pre>
            <p>Cette propriété est héritée pour tous les fils en-ligne de l'élément.</p>
            <h3>2. Centrez horizontalement</h3>
            <h4>Les éléments de type Block</h4>
            <p>Nous pouvons leur appliquer une margin et ainsi en fixant margin-left et margin-right à "auto".</p>
            <pre class="prettyprint">
margin-left: auto;
margin-right: auto;
            </pre>
            <h3>3. Centrez verticalement</h3>
            <h4>Line-height</h4>
            <pre class="prettyprint">
text-align: center;
            </pre>
            <p>Cette propriété est héritée pour tous les fils en-ligne de l'élément.</p>
            <h4>Inline-block</h4>
            <p>Nous pouvons leur appliquer une margin et ainsi en fixant margin-left et margin-right à "auto".</p>
            <pre class="prettyprint">
margin-left: auto;
margin-right: auto;
            </pre>

      		</div>
      		<div class="tab-pane" id="troubleshooting">
            <div class='row'>
              <div class="col-xs-2">
              	<br>
                <p><i class="fa fa-sort-desc"></i> MonSite</p>
                <p class="tab"><i class="fa fa-sort-desc"></i> css</p>
                <p class="tab2">cpi2.css</p>
                <p class="tab">index.html</p>
              </div>
              <div class="col-xs-10">
                <div class="tabbable subtab">
                  <ul class="nav nav-tabs">
                    <li class="active">
                      <a data-toggle="tab" href="#html">index.html</a>
                    </li>
                    <li>
                      <a data-toggle="tab" href="#css">cpi2.css</a>
                    </li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active" id="html">
                      <br>
                      <pre class="prettyprint">
&lt;!doctype html&gt;
&lt;html&gt;
 &lt;head&gt;
  &lt;title&gt;CPi selfies&lt;/title&gt;
  &lt;meta charset=&quot;utf-8&quot;&gt;
		
  &lt;!-- J&#039;inclus le CSS de Bootstrap --&gt;
  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css&quot;&gt;
  &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;assets/cpi2.css&quot;&gt;
 &lt;/head&gt;
 &lt;body&gt;
  &lt;!-- Contenu de votre site --&gt;



  &lt;!-- J&#039;inclus jQuery dont le JavaScript de Bootstrap a besoin --&gt;
	&lt;script src="http://code.jquery.com/jquery-1.11.0.min.js"&gt; &lt;/script&gt;
  &lt;!-- J&#039;inclus le JavaScript de Bootstrap a besoin --&gt;
	&lt;script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"&gt; &lt;/script&gt;
 &lt;/body&gt;
&lt;/html&gt;
                      </pre>
                    </div>
                    <div class="tab-pane" id="css">
                      <br>
                      <pre class="prettyprint">
/*Rien de particulier ici*/
                      </pre>
                    </div>



                  </div>
                </div>
              </div>
            </div>
          </div>                    
      		<%= render 'layouts/lessons/disqus' %>
    		</div>
    	</div>
    </div>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        prettyPrint();
      });
    </script>
  </body>
</html>